stages:
  - lint
  - build
  - test

default:
  image: node:20-alpine
  before_script:
    - apk add --no-cache git # Install Git
    - corepack enable
    - cd backend
    - npm install
    - export NX_HEAD=$CI_COMMIT_SHA
    - export NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

variables:
  GIT_DEPTH: 0

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

.lint-test-build-template:
  interruptible: true
  only:
    - merge_requests
    - main
    - CICD
    - featues/*
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t $NX_TASK

lint:
  extends: .lint-test-build-template
  stage: lint
  variables:
    NX_TASK: lint

test:
  extends: .lint-test-build-template
  stage: test
  variables:
    NX_TASK: test

build:
  extends: .lint-test-build-template
  stage: build
  variables:
    NX_TASK: build
