version: '2'

services:
  db:
    image: postgres:16.4
    container_name: clv_postgres
    environment:
      #Khi dựng trên Dbeaver chỉ phụ thuộc username và pass
      POSTGRES_USER: root #Đặt root để ko bị báo lỗi từ docker
      POSTGRES_PASSWORD: 130600 
      POSTGRES_DB: root #Đặt root để ko bị báo lỗi từ docker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgreSql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s # Khoảng tg của các lần kiểm tra 
      timeout: 5s # tg tối đa mà lệnh kiểm tra có thể chạy trc khi bị đánh dấu là không thành công
      retries: 10
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: apps/authentication/Dockerfile # Dockerfile cho ứng dụng auth
    depends_on:
      - db
    ports:
      - "3001:13001"  # Mở cổng 3001 từ container auth ra ngoài
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile # Dockerfile cho ứng dụng notification
    ports:
      - "3002:13000"  # Mở cổng 3002 từ container notification ra ngoài
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: nginx/Dockerfile # Dockerfile cho ứng dụng notification
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.config  # Mount file nginx.conf vào container Nginx
    ports:
      - "3000:3000"  # Nginx sẽ lắng nghe trên cổng 3000
    depends_on:
      - auth
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  pgdata: